#!/bin/sh
# Module: kernel.core_fingerprint
# Purpose: Include Rust implementation changes in the kernel module identity.
# Created: 2026-10-01
# Architecture: Kbuild generates a C header from this digest; modpost then
# accounts for the Rust core when computing ntfs_rs's source version.

set -eu
cd -- "$(dirname -- "$0")/.."

# Hash relative names in stable order so source extraction paths do not alter
# the identity. These are the Rust modules compiled into the kernel adapter.
fingerprint=$(
    find src/crypto src/engine src/ondisk src/ops \
        -type f -name '*.rs' -print0 |
        LC_ALL=C sort -z |
        xargs -0 sha256sum
    sha256sum src/format.rs kernel/ntfs_parser.rs kernel/writer.rs kernel/freestanding.rs
)
fingerprint=$(printf '%s\n' "$fingerprint" | sha256sum | cut -d ' ' -f 1)
printf '/* Generated by kernel.core_fingerprint; do not edit. */\n'
printf '#define NTFS_RS_CORE_HASH "%s"\n' "$fingerprint"
